# Generated by Django 4.2.6 on 2023-10-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
